[package]
name = "partner-chains-plutus-data"
version = "1.7.0"
description = "Parsing and serialization of Plutus data schemas used by Partner Chains smart contracts."
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
log = { workspace = true }
sidechain-domain = { workspace = true, features = ["std"] , version = "1.7.0" }

cardano-serialization-lib = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
raw-scripts = { workspace = true }
serde_json = { workspace = true }
hex-literal = { workspace = true }
pretty_assertions = { workspace = true }
