[package]
name = "pallet-session-validator-management-rpc"
version = "1.7.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
derive-new = { workspace = true }
jsonrpsee = { workspace = true }
sidechain-domain = { workspace = true, features = ["std"] , version = "1.7.0" }
sp-session-validator-management-query = { workspace = true , version = "1.7.0" }
