[package]
name = "pallet-session-validator-management-rpc"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
derive-new = { workspace = true }
jsonrpsee = { workspace = true }
sidechain-domain = { workspace = true, default-features = true }
sp-session-validator-management-query = { workspace = true, default-features = true }
