name: "Install kubectl, helm, and awscli"
description: "Install kubectl, helm, and awscli tools for Kubernetes deployment"

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install kubectl, helm, and awscli
      run: |
        set -euo pipefail
        
        # Install base packages
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl python3-pip
        sudo update-ca-certificates
        
        # Install Helm via APT
        sudo apt-get install -y apt-transport-https
        echo "deb [arch=amd64 trusted=yes] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update -y
        sudo apt-get install -y helm

        # Install kubectl
        curl -fsSL -o kubectl "https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl

        # Install AWS CLI
        pip3 install --upgrade awscli
      shell: bash
