name: "Install kubectl, helm, and awscli"
description: "Install kubectl, helm, and awscli tools for Kubernetes deployment"

runs:
  using: "composite"
  steps:
    - name: Install kubectl, helm, and awscli (resilient, no GPG checks)
      shell: bash
      run: |
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive

        echo "--- Updating base packages ---"
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl python3-pip

        echo "--- Installing Helm directly ---"
        # get latest release version
        HELM_VERSION=$(curl -s https://api.github.com/repos/helm/helm/releases/latest | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/')
        echo "Installing Helm v${HELM_VERSION}"

        # try primary URL, fallback to GitHub if needed
        curl -fsSL --retry 5 --retry-delay 3 -o helm.tar.gz \
          "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" || \
        curl -fsSL -o helm.tar.gz \
          "https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz"

        tar -xzf helm.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm
        rm -rf linux-amd64 helm.tar.gz
        helm version || echo "Helm installed (version check skipped)"

        echo "--- Installing kubectl ---"
        KUBECTL_VER="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
        curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 -o kubectl \
          "https://dl.k8s.io/release/${KUBECTL_VER}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        kubectl version --client=true || echo "kubectl installed"

        echo "--- Installing AWS CLI ---"
        pip3 install --upgrade awscli
        aws --version || echo "awscli installed"
