name: "Install kubectl, helm, and awscli"
description: "Install kubectl, helm, and awscli tools for Kubernetes deployment"

runs:
  using: "composite"
  steps:
    - name: Install kubectl, helm, and awscli (Ubuntu 24.04)
      shell: bash
      run: |
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive

        echo "--- Updating base packages ---"
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl python3-pip snapd
        sudo update-ca-certificates

        echo "--- Installing Helm via Snap ---"
        sudo snap install helm --classic
        helm version

        echo "--- Installing kubectl ---"
        KUBECTL_VER="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
        curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 -o kubectl \
          "https://dl.k8s.io/release/${KUBECTL_VER}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        kubectl version --client=true

        echo "--- Installing AWS CLI ---"
        pip3 install --upgrade awscli
        aws --version
