name: "Install kubectl, helm, and awscli"
description: "Install kubectl, helm, and awscli tools for Kubernetes deployment"

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install kubectl, helm, and awscli (minimal, no checksums)
      shell: bash
      run: |
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive

        # Base packages
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl python3-pip
        sudo update-ca-certificates

        # Install Helm
        HELM_VERSION=$(curl -s https://api.github.com/repos/helm/helm/releases/latest | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/')
        echo "Installing Helm v${HELM_VERSION}"
        curl -fsSL -o helm.tar.gz "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz"
        tar -xzf helm.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm
        rm -rf linux-amd64 helm.tar.gz
        helm version

        # Install kubectl
        KUBECTL_VER="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
        curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 -o kubectl "https://dl.k8s.io/release/${KUBECTL_VER}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        kubectl version --client=true

        # Install AWS CLI
        pip3 install --upgrade awscli
        aws --version
