[package]
name = "sidechain-slots"
version = "1.2.0"
authors = ["IOG"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/input-output-hk/partner-chains"
description = "Sidechain slots and epoch calcuations"
readme = "README.md"

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sidechain-domain = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true, optional = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true, features = ["serde"]}
sp-consensus-slots = { workspace = true }
serde = { workspace = true, optional = true }
envy = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ['std']
std = [
    'sidechain-domain/std',
    'scale-info/std',
    'sp-api/std',
	'sp-blockchain',
    'sp-core/std',
    'sp-consensus-slots/std',
    'envy'
]
serde = [
    "dep:serde",
    "scale-info/serde",
    "sp-core/serde",
]
