[package]
name = "sp-block-producer-metadata"
version.workspace = true
license = "Apache-2.0"
description = "Primitives for the block producer on-chain metadata feature"
readme = "README.md"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sidechain-domain = { workspace = true }
parity-scale-codec = { workspace = true }
secp256k1 = { workspace = true, features = ["global-context", "hashes"] }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default = ["std"]
std = [
    "sidechain-domain/std",
    "secp256k1/std",
]
