[package]
name = "sp-block-producer-metadata"
version.workspace = true
license = "Apache-2.0"
description = "Primitives for the block producer on-chain metadata feature"
readme = "README.md"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sidechain-domain = { workspace = true }
sp-api = { workspace = true }
parity-scale-codec = { workspace = true }
k256 = { workspace = true,features = ["sha256"] }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default = ["std"]
std = [
    "sidechain-domain/std",
    "k256/std",
    "sp-api/std",
    "parity-scale-codec/std",
]
