chain:
  cardano_network: "preview"
  keystore_network: "staging"
  block_stability_margin: "0"
  chainspec_secretName: ""
  chainspec_filename: "staging_preview_chain_spec.json"
images:
  cardanoNode: "ghcr.io/intersectmbo/cardano-node:10.1.2"
  postgres: "postgres:15.3"
  dbSync: "ghcr.io/intersectmbo/cardano-db-sync:13.5.0.2"
  substrateNode: ""
