name: "Build and Publish to ECR"
description: "Builds the partner-chains-node Docker image and pushes it to ECR."
inputs:
  sha:
    description: "Commit SHA"
    required: true
  tag:
    description: "Release Tag"
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Download partner-chains-node-x86_64-linux-artifact
      uses: actions/download-artifact@v4
      with:
        name: partner-chains-node-x86_64-linux-artifact

    - name: Create and Configure Docker Container
      id: create-container
      run: |
        container_id=$(docker run -d debian:bullseye-slim sleep infinity)
        echo "container_id=$container_id" >> $GITHUB_ENV
        docker exec $container_id useradd -m -u 1000 -U -s /bin/sh -d /substrate substrate
        docker exec $container_id mkdir -p /data /substrate/.local/share/partner-chains-node
        docker exec $container_id chown -R substrate:substrate /data /substrate
        docker exec $container_id rm -rf /usr/bin/apt* /usr/bin/dpkg*
        docker exec $container_id ln -s /data /substrate/.local/share/partner-chains-node
        docker cp ./partner-chains-node-${{ inputs.tag }}-x86_64-linux $container_id:/usr/local/bin/partner-chains-node
        docker commit --change='EXPOSE 30333 9615 9933 9944' --change='ENTRYPOINT ["/usr/local/bin/partner-chains-node"]' $container_id substrate-node:${{ inputs.sha }}
      shell: bash

    - name: Cleanup Docker Container
      if: always()
      run: |
        docker rm -f ${{ env.container_id }}
      shell: bash

    - name: Acquire AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN_SECRET }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ECR_REGISTRY_SECRET }}

    - name: Push to ECR
      run: |
        docker tag substrate-node:${{ inputs.sha }} ${{ env.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }}
        docker push ${{ env.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }}
      shell: bash