[package]
name = "cli-commands"
version = "1.6.1"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ed25519-zebra = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
plutus = { workspace = true }
plutus-datum-derive = { workspace = true }
secp256k1 = { workspace = true, features = ["std", "global-context"] }
sidechain-domain = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pallet-address-associations = { workspace = true, features = ["std"] }
parity-scale-codec = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
