[package]
name = "cli-commands"
version = "1.6.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-zebra = { workspace = true }
hex = { workspace = true }
secp256k1 = { workspace = true, features = ["std", "global-context"] }
sidechain-domain = { workspace = true, default-features = true, features = [
	"std",
] }
thiserror = { workspace = true }
