[package]
name = "cli-commands"
version = "1.7.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ed25519-zebra = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
plutus = { workspace = true , version = "1.7.0" }
plutus-datum-derive = { workspace = true , version = "1.7.0" }
secp256k1 = { workspace = true, features = ["std", "global-context"] }
k256 = { workspace = true, features = ["serde"] }
sidechain-domain = { workspace = true, features = ["std"] , version = "1.7.0" }
sp-io = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pallet-address-associations = { workspace = true, features = ["std"] , version = "1.7.0" }
parity-scale-codec = { workspace = true }
sp-block-producer-metadata = { workspace = true, features = ["std"] , version = "1.7.0" }

[dev-dependencies]
assert_cmd = { workspace = true }
pretty_assertions = { workspace = true }
