[package]
name = "sp-stake-distribution"
version = "1.5.0"
edition = "2021"
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true, optional = true }
sidechain-domain = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
default = ["std"]
std = ["async-trait", "sidechain-domain/std"]
mock = []
