[package]
name = "pallet-session-validator-management-benchmarking"
version = "1.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-consensus-aura = { workspace = true }
sidechain-domain = { workspace = true }
sidechain-slots = { workspace = true }
frame-benchmarking = { workspace = true }

pallet-aura = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-sidechain = { workspace = true }
pallet-session-validator-management = { workspace = true }

[dev-dependencies]
chain-params = { workspace = true }
sp-io = { workspace = true }
serde = { workspace = true }
mock-types = { workspace = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
	"scale-info/std",
	"frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-core/std",
	"sp-io/std",
    "sp-consensus-slots/std",
	"sp-consensus-aura/std",
	"sidechain-domain/std",
    "sidechain-slots/std",
	"pallet-timestamp/std",
	"pallet-aura/std",
	"pallet-sidechain/std",
	"pallet-session-validator-management/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
