[package]
name = "schnorr_jubjub"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
midnight-circuits = { git = "https://github.com/midnightntwrk/midnight-circuits", branch = "iquerejeta/committee_proof"}
halo2curves = { version = "0.7.0", features = ["derive_serde"] }
blstrs = { git = "https://github.com/davidnevadoc/blstrs", rev = "3dfe5bf" }
group = "0.13"
ff = "0.13"
frame-support = { workspace = true }
pallet-beefy-mmr = { workspace = true }
parity-scale-codec = { workspace = true }
rand_core = "0.6.4"
scale-info = {workspace = true}
sc-keystore = { workspace = true }
sp-core = { workspace = true }
sp-application-crypto = { workspace = true }
sp-consensus-beefy = { workspace = true }
sp-runtime = { workspace = true }
sp-runtime-interface = { workspace = true }
sp-io = { workspace = true }
sp-keystore = { workspace = true }
sp-externalities = { workspace = true }
sha2 = "0.10.9"
serde = {workspace = true }
hex = {workspace = true }

[lints]
workspace = true
