[package]
name = "schnorr_jubjub"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
frame-support = { workspace = true }
pallet-beefy-mmr = { workspace = true }
parity-scale-codec = { workspace = true }
rand_core = { workspace = true }
scale-info = {workspace = true}
sc-keystore = { workspace = true }
sp-core = { workspace = true, features = ["serde"] }
sp-application-crypto = { workspace = true }
sp-consensus-beefy = { workspace = true }
sp-runtime = { workspace = true }
sp-runtime-interface = { workspace = true }
sp-io = { workspace = true }
sp-keystore = { workspace = true }
sp-externalities = { workspace = true }
sha2 = { workspace = true }
serde = {workspace = true }
hex = {workspace = true }
hash256-std-hasher = { workspace = true }
sp-trie = { workspace = true }
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
#rand = { workspace = true }
#rand_chacha = { workspace = true }
ark-ed-on-bls12-381 = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true }


[features]
default = ["std"]
std = [
    "ark-ed-on-bls12-381/std",
    "ark-ff/std",
    "ark-ec/std",
    "ark-serialize/std",
    "frame-support/std",
    "pallet-beefy-mmr/std",
    "parity-scale-codec/std",
    "rand_core/std",
    "scale-info/std",
    "sp-core/std",
    "sp-application-crypto/std",
    "sp-consensus-beefy/std",
    "sp-runtime/std",
    "sp-runtime-interface/std",
    "sp-io/std",
    "sp-keystore/std",
    "sp-externalities/std",
    "sha2/std",
    "serde/std",
    "hex/std",
    "hash256-std-hasher/std",
    "sp-trie/std",
    "rand/std",
    "rand_chacha/std",
]

[lints]
workspace = true
