[package]
name = "partner-chains-node-commands"
version = "1.5.0"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
authority-selection-inherents = { workspace = true }
clap = { workspace = true }
cli-commands = { workspace = true }
env_logger = { workspace = true }
frame-support = { workspace = true }
log = { workspace = true }
log4rs = { workspace = true }
parity-scale-codec = { workspace = true }
partner-chains-cli = { workspace = true }
partner-chains-smart-contracts-commands = { workspace = true }
plutus = { workspace = true }
sidechain-domain = { workspace = true, default-features = true }
sc-cli = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-sidechain = { workspace = true, default-features = true }
sp-session-validator-management = { workspace = true }
sp-session-validator-management-query = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
