
//! Autogenerated weights for pallet_block_participation
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.0.0
//! DATE: 2025-02-28, STEPS: `5000`, REPEAT: `2000`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Nikolaoss-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/sidechain-runtime/sidechain_runtime.compact.compressed.wasm
// --pallet
// pallet_block_participation
// --extrinsic
// *
// --steps=5000
// --repeat=2000
// --wasm-execution=compiled
// --output
// toolkit/pallets/block-participation/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_block_participation.
pub trait WeightInfo {
	fn note_processing() -> Weight;
}

/// Weights for pallet_block_participation using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `BlockProductionLog::Log` (r:1 w:1)
	/// Proof: `BlockProductionLog::Log` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn note_processing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(8_000_000, 1491)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `BlockProductionLog::Log` (r:1 w:1)
	/// Proof: `BlockProductionLog::Log` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn note_processing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(8_000_000, 1491)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
