name: "Generate Chain Specs from Node Binary"
description: "Downloads the partner-chains node binary, generates chain specs for different environments, and uploads them."
inputs:
  tag:
    description: "Node tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download partner-chains-node-linux-artifact
      uses: actions/download-artifact@v4
      with:
        name: partner-chains-node-linux-artifact
        path: ./
    - name: Generate Chain Specs
      shell: bash
      run: |
        chmod +x partner-chains-node-${{ inputs.tag }}-x86_64-linux
        source ./dev/envs/devnet/.envrc
        ./partner-chains-node-${{ inputs.tag }}-x86_64-linux build-spec --chain local --disable-default-bootnode > devnet_chain_spec.json
        source ./dev/envs/staging-preview/.envrc
        ./partner-chains-node-${{ inputs.tag }}-x86_64-linux build-spec --chain staging --disable-default-bootnode > staging_preview_chain_spec.json
        source ./dev/envs/staging-preprod/.envrc
        ./partner-chains-node-${{ inputs.tag }}-x86_64-linux build-spec --chain staging --disable-default-bootnode > staging_preprod_chain_spec.json
    - name: Upload Chain Specs
      uses: actions/upload-artifact@v4
      with:
        name: chain-specs
        path: |
          devnet_chain_spec.json
          staging_preview_chain_spec.json
          staging_preprod_chain_spec.json
