name: "Publish Release"
description: "Publishes a GitHub release from draft status."
inputs:
  tag:
    description: "Tag for the release"
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Check if release exists
      id: check_release
      run: |
        tag="${{ inputs.tag }}"
        release_response=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
        if echo "$release_response" | grep -q '"message": "Not Found"'; then
          echo "release_exists=false" >> $GITHUB_ENV
          echo "::set-output name=release_exists::false"
        else
          echo "release_exists=true" >> $GITHUB_ENV
          echo "::set-output name=release_exists::true"
          echo "release_id=$(echo $release_response | jq -r .id)" >> $GITHUB_ENV
          echo "::set-output name=release_id::$(echo $release_response | jq -r .id)"
        fi
      shell: bash

    - name: Publish release
      if: ${{ steps.check_release.outputs.release_exists == 'true' }}
      run: |
        release_id="${{ steps.check_release.outputs.release_id }}"
        curl -s -X PATCH -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          -d '{"draft": false}' \
          "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
      shell: bash