name: "Publish Release"
description: "Publishes a GitHub release from draft status."
inputs:
  tag:
    description: "Tag for the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}