name: "Upload Artifacts to S3"
description: "Upload built artifacts to an S3 bucket"
inputs:
  sha:
    description: "Commit SHA for naming artifacts"
    required: true
  bucket-name:
    description: "S3 bucket name"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install AWS CLI
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Upload Artifacts to S3
      shell: bash
      run: |
        ARTIFACTS_DIR="artifacts"
        S3_BUCKET_NAME="${{ inputs.bucket-name }}"
        S3_UPLOAD_PATH="artifacts/${{ inputs.sha }}"

        for artifact in $ARTIFACTS_DIR/*; do
          aws s3 cp "$artifact" "s3://$S3_BUCKET_NAME/$S3_UPLOAD_PATH/$(basename "$artifact")"
        done
