name: "Upload Artifacts to S3"
description: "Upload built artifacts to an S3 bucket"
inputs:
  sha:
    description: "Commit SHA for naming artifacts"
    required: true
  bucket-name:
    description: "S3 bucket name"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Acquire AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN_SECRET }}
        aws-region: eu-central-1

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Upload Artifacts to S3
      shell: bash
      run: |
        ARTIFACTS_DIR="artifacts"
        S3_BUCKET_NAME="${{ inputs.bucket-name }}"
        S3_UPLOAD_PATH="artifacts/${{ inputs.sha }}"
    
        echo "Uploading artifacts to S3 at path: s3://$S3_BUCKET_NAME/$S3_UPLOAD_PATH/"
        aws s3 sync "$ARTIFACTS_DIR" "s3://$S3_BUCKET_NAME/$S3_UPLOAD_PATH/"
        echo "Artifacts successfully uploaded to s3://$S3_BUCKET_NAME/$S3_UPLOAD_PATH/"

