[package]
name = "pallet-session-validator-management-rpc"
version = "1.1.0"
edition = "2021"

[dependencies]
derive-new = { workspace = true }
jsonrpsee = { workspace = true }
sidechain-domain = { workspace = true, default-features = true }
sp-session-validator-management-query = { workspace = true, default-features = true }
