[package]
name = "sidechain-block-search"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { workspace = true, features = ['std'] }
scale-info = { workspace = true, features = ['std'] }
serde = { workspace = true, default-features = true }

sp-core = { workspace = true, features = ['std'] }
sp-runtime = { workspace = true, features = ['std'] }
sp-api = { workspace = true, features = ['std'] }
sp-blockchain = { workspace = true }

sp-sidechain = { workspace = true, features = ['std'] }
sidechain-domain = { workspace = true, features = ['std'] }
hex = { workspace = true, features = ['std'] }

[dev-dependencies]
proptest = { workspace = true }
hex-literal = { workspace = true }
sp-consensus-aura = { workspace = true, features = ['std'] }
sp-consensus-slots = { workspace = true, features = ['std'] }
