[net]
git-fetch-with-cli = true

[target.'cfg(target_os = "linux")']
linker    = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "relocation-model=static",
]
