[package]
name = "pallet-sidechain-rpc"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { workspace = true, features = ['std'] }
scale-info = { workspace = true, features = ['std'] }
jsonrpsee = { workspace = true }
serde = { workspace = true, default-features = true }

sp-core = { workspace = true, features = ['std'] }
sp-runtime = { workspace = true, features = ['std'] }
sp-api = { workspace = true, features = ['std'] }
sp-blockchain = { workspace = true }

sp-sidechain = { workspace = true, features = ['std'] }
sidechain-domain = { workspace = true, features = ['std'] }
sidechain-slots = { workspace = true, features = ['std'] }
main-chain-follower-api = { workspace = true, features = ['std', 'block-source'] }
serde_json = { workspace = true, features = ['std'] }
sp-timestamp = { workspace = true, features = ['std'] }
hex = { workspace = true, features = ['std'] }
tokio = { workspace = true, features = ["macros", "time", "parking_lot"] }
epoch-derivation = { workspace = true, features = ['std'] }
time-source = { workspace = true }
derive-new = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
pretty_assertions = { workspace = true }
time-source = { workspace = true, features = ['mock'] }
sp-consensus-slots = { workspace = true, features = ["std"] }

[features]
default = []
