[package]
name = "sp-session-validator-management"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epoch-derivation = { workspace = true }
scale-info = { workspace = true }
parity-scale-codec = { workspace = true }
serde = { workspace = true, optional = true }
sidechain-domain = { workspace = true }
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
thiserror = { workspace = true, optional = true }
envy = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    "epoch-derivation/std",
    "parity-scale-codec/std",
    "sp-api/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-std/std",
    "sp-runtime/std",
    "thiserror",
    "envy"
]
serde = [
	"dep:serde",
	"scale-info/serde",
	"sidechain-domain/serde",
]
