
//! Autogenerated weights for pallet_governed_map
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.0.0
//! DATE: 2025-04-11, STEPS: `500`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Nikolaoss-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/partner-chains-demo-runtime/partner_chains_demo_runtime.compact.compressed.wasm
// --pallet
// pallet_governed_map
// --extrinsic
// *
// --steps=500
// --repeat=200
// --wasm-execution=compiled
// --output
// toolkit/governed-map/pallet/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_governed_map.
pub trait WeightInfo {
	fn register_changes() -> Weight;
	fn set_main_chain_scripts() -> Weight;
}

/// Weights for pallet_governed_map using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `GovernedMap::Mapping` (r:0 w:4)
	/// Proof: `GovernedMap::Mapping` (`max_values`: None, `max_size`: Some(588), added: 3063, mode: `MaxEncodedLen`)
	fn register_changes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `GovernedMap::MainChainScripts` (r:0 w:1)
	/// Proof: `GovernedMap::MainChainScripts` (`max_values`: Some(1), `max_size`: Some(183), added: 678, mode: `MaxEncodedLen`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `GovernedMap::Mapping` (r:0 w:4)
	/// Proof: `GovernedMap::Mapping` (`max_values`: None, `max_size`: Some(588), added: 3063, mode: `MaxEncodedLen`)
	fn register_changes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `GovernedMap::MainChainScripts` (r:0 w:1)
	/// Proof: `GovernedMap::MainChainScripts` (`max_values`: Some(1), `max_size`: Some(183), added: 678, mode: `MaxEncodedLen`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
