{{- $root := . -}}
{{- range $podName, $podValues := .Values.pods }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $podName }}
  namespace: {{ $podValues.pod.namespace }}
  labels:
    app: sidechains-substrate-poc
    node: {{ $podName }}
    substrate-node: 'true'
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9615'
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: substrate-node
            operator: In
            values:
            - 'true'
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    topology.kubernetes.io/zone: {{ $podValues.infrastructure.zone }}
  containers:
    - name: cardano-node
      image: {{ $root.Values.images.cardanoNode }}
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "1000m"
        requests:
          memory: "4096Mi"
          cpu: "1000m"
      env:
        - name: NETWORK
          value: "{{ $root.Values.chain.cardano_network }}"
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
      volumeMounts:
        - name: ipc
          mountPath: /ipc
        - name: cardano-node-data
          mountPath: /data
    - name: db-sync
      image: {{ $root.Values.images.dbSync }}
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "500m"
        requests:
          memory: "4096Mi"
          cpu: "500m"
      env:
        - name: NETWORK
          value: "{{ $root.Values.chain.cardano_network }}"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: ipc
          mountPath: /node-ipc
        - name: db-sync-state-dir
          mountPath: /var/lib
    - name: postgres
      image: {{ $root.Values.images.postgres }}
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "2048Mi"
          cpu: "500m"
        requests:
          memory: "2048Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-sharedmemory
          mountPath: /dev/shm
    - name: substrate-node
      image: {{ $root.Values.images.substrateNode }}
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "1000m"
        requests:
          memory: "4096Mi"
          cpu: "1000m"
      env:
        - name: DB_SYNC_POSTGRES_CONNECTION_STRING
          value: "postgres://postgres:password123@localhost/cexplorer"
        - name: CARDANO_SECURITY_PARAMETER
          value: "432"
        - name: CARDANO_ACTIVE_SLOTS_COEFF
          value: "0.05"
        - name: MC__FIRST_EPOCH_TIMESTAMP_MILLIS
          value: "1666656000000"
        - name: MC__FIRST_EPOCH_NUMBER
          value: "0"
        - name: MC__FIRST_SLOT_NUMBER
          value: "0"
        - name: MC__EPOCH_DURATION_MILLIS
          value: "86400000"
        - name: SIDECHAIN_BLOCK_BENEFICIARY
          value: "{{ $podValues.pod.containers.substrateNode.nodeKey }}"
        - name: BLOCK_STABILITY_MARGIN
          value: "{{ $root.Values.chain.block_stability_margin }}"
      args:
        {{- if $podValues.pod.containers.substrateNode.validator }}
        - "--validator"
        {{- end }}
        - "--chain"
        - "/chain-spec/{{ $root.Values.chain.chainspec_filename }}"
        - "--node-key"
        - "{{ $podValues.pod.containers.substrateNode.nodeKey }}"
        - "--bootnodes"
        - "{{ $podValues.pod.containers.substrateNode.bootNodes }}"
        - "--base-path"
        - "/data"
        - "--unsafe-rpc-external"
        - "--rpc-port"
        - "9933"
        - "--rpc-cors=all"
        - "--prometheus-port"
        - "9615"
        - "--prometheus-external"
        - "--state-pruning"
        - "archive"
        - "--blocks-pruning"
        - "archive"
      ports:
        - containerPort: 30333
          name: p2p
        - containerPort: 9945
          name: ws-port
        - containerPort: 9933
          name: rpc-port
        - containerPort: 9615
          name: prometheus
      volumeMounts:
        - name: substrate-node-data
          mountPath: /data
        - name: ipc
          mountPath: /ipc
        {{- if $podValues.pod.containers.substrateNode.validator }}
        - name: keystore-volume
          mountPath: /data/chains/{{ $root.Values.chain.keystore_network }}/keystore
        {{- end }}
        - name: chain-spec
          mountPath: /chain-spec
  volumes:
    - name: cardano-node-data
      persistentVolumeClaim:
        claimName: {{ $podName }}-claim-cardano-node-data
    - name: postgres-data
      persistentVolumeClaim:
        claimName: {{ $podName }}-claim-postgres-data
    - name: postgres-sharedmemory
      emptyDir:
        medium: Memory
        sizeLimit: "2Gi"
    - name: substrate-node-data
      persistentVolumeClaim:
        claimName: {{ $podName }}-claim-substrate-node-data
    - name: db-sync-state-dir
      persistentVolumeClaim:
        claimName: {{ $podName }}-claim-db-sync-state-dir
    - name: ipc
      emptyDir: {}
    {{- if $podValues.pod.containers.substrateNode.validator }}
    - name: keystore-volume
      secret:
        secretName: {{ $podValues.pod.containers.substrateNode.keystore_secret_name }}
    {{- end }}
    - name: chain-spec
      secret:
        secretName: {{ $root.Values.chain.chainspec_secretName }}
{{- end }}
