{{- $root := . -}}
{{- range $podName, $podValues := .Values.pods }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $podName }}-claim-cardano-node-data
  namespace: {{ $podValues.pod.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $podName }}-cardano-node-data-storageclass 
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $podName }}-claim-postgres-data
  namespace: {{ $podValues.pod.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $podName }}-postgres-data-storageclass 
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $podName }}-claim-substrate-node-data
  namespace: {{ $podValues.pod.namespace }}
spec:
  accessModes:
    - ReadWriteMany
    #- ReadWriteOnce
  storageClassName: aws-efs-storageclass
  #storageClassName: {{ $podName }}-substrate-node-data-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $podName }}-claim-db-sync-state-dir
  namespace: {{ $podValues.pod.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $podName }}-db-sync-state-dir-storageclass
  resources:
    requests:
      storage: 10Gi
{{- end }}
