pods:
  alice:
    infrastructure:
      zone: eu-central-1a
    service:
      nodePorts:
        p2p: 30001
        rpc: 30021
    pod:
      namespace: sc
      containers:
        substrateNode:
          nodeKey: "0000000000000000000000000000000000000000000000000000000000000001"
          bootNodes: "/dns/bob-service.sc.svc.cluster.local/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
          validator: true
          keystore_secret_name: devnet-alice-keystore
