pods:
  henry:
    infrastructure:
      zone: eu-central-1c
    service:
      nodePorts:
        p2p: 30008
        rpc: 30028
    pod:
      namespace: sc
      containers:
        substrateNode:
          nodeKey: "0000000000000000000000000000000000000000000000000000000000000008"
          bootNodes: "/dns/alice-service.sc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
          validator: true
          keystore_secret_name: devnet-henry-keystore
