name: "Create Draft Release"
description: "Creates a draft release on GitHub."
inputs:
  tag:
    description: "Tag for the release"
    required: true
  sha:
    description: "SHA of the commit"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check if release already exists
      id: check_release
      run: |
        tag="${{ inputs.tag }}"
        echo "Checking if release with tag $tag exists..."
        release_response=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
        if echo "$release_response" | grep -q '"message": "Not Found"'; then
          echo "Release with tag $tag does not exist. Proceeding to create a new draft release."
          echo "release_exists=false" >> $GITHUB_OUTPUT
          echo "release_id=" >> $GITHUB_OUTPUT
        else
          echo "Release with tag $tag already exists."
          echo "release_exists=true" >> $GITHUB_OUTPUT
          echo "release_id=$(echo $release_response | jq -r .id)" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Checkout specific SHA
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha }}
        path: release-sha
    - name: Create draft release
      id: create_release
      if: ${{ steps.check_release.outputs.release_exists == 'false' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: "Partner Chains Node ${{ inputs.tag }}"
        draft: true
        prerelease: true
        generate_release_notes: false
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}