[package]
name = "sp-governed-map"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
license = "Apache-2.0"
description = "Primitives for tracking the governed key-value store on main chain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true, optional = true }
log = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true, optional = true }
sidechain-domain = { workspace = true }
sp-api = { workspace = true }
sp-inherents = { workspace = true }
sp-runtime = { workspace = true }
thiserror = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
pretty_assertions = { workspace = true }

[features]
default = ["std"]
std = [
    "async-trait",
    "log/std",
    "scale-info/std",
    "serde",
    "sidechain-domain/std",
    "sp-api/std",
    "sp-inherents/std",
    "sp-runtime/std",
    "thiserror",
]
serde = [
	"dep:serde",
	"scale-info/serde",
	"sidechain-domain/serde",
]
mock = []
