[package]
name = "pallet-session-keys-registration"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
license = "Apache-2.0"
description = "Pallet for registering session keys for the partner chains"

[lints]
workspace = true

[dependencies]
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true, default-features = false, features = [
    "derive",
] }
sp-runtime = { workspace = true, default-features = false }
pallet-session = { workspace = true }

[dev-dependencies]
pallet-staking = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-staking = { workspace = true }
sp-tracing = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-runtime/std",
    "pallet-session/std",
    "pallet-staking/std",
]
