name: "Deploy Rust Docs"
description: "Installs necessary tooling, generates Rust documentation, and deploys it to GitHub Pages."
inputs:
  ssh_key:
    description: "SSH key to read Substrate Repo"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Build Rustdocs 
      run: |
        nix develop .#nightly -c gen-cargo-docs
      shell: bash

    - name: Deploy documentation
      if: ${{ github.ref_name == 'master' }}
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc

