name: "Deploy Rust Docs"
description: "Installs necessary tooling, generates Rust documentation, and deploys it to GitHub Pages."
inputs:
  ssh_key:
    description: "SSH key to read Substrate Repo"
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add SSH key to read Substrate Repo
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        ssh-add - <<< "${{ inputs.ssh_key }}"
      shell: bash

    - name: Install Nix
      run: |
        sh <(curl -L https://nixos.org/nix/install) --daemon
        . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      shell: bash
    
    - name: Build rustdocs
      run: |
        . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        export NIX_CONFIG="experimental-features = nix-command flakes"
        nix develop .#nightly -c gen-cargo-docs
      shell: bash

    - name: Deploy documentation
      if: ${{ github.ref_name == 'master' }}
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
