[package]
name = "partner-chains-dolos-data-sources"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Dolos-based implementations of all data sources used by Partner Chains components"

[lints]
workspace = true

[dependencies]
sidechain-domain = { workspace = true, features = ["std", "serde"] }
async-trait = { workspace = true }
sp-timestamp = { workspace = true, features = ["std"] }
sp-governed-map = { workspace = true, features = ["std"], optional = true }
sidechain-mc-hash = { workspace = true, optional = true }
pallet-sidechain-rpc = { workspace = true, optional = true }
authority-selection-inherents = { workspace = true, features = [
    "std",
], optional = true }
sp-block-participation = { workspace = true, features = [
    "std",
], optional = true }
sp-partner-chains-bridge = { workspace = true, optional = true, features = [
    "std",
] }

[features]
default = []
block-source = []
candidate-source = ["authority-selection-inherents"]
governed-map = ["sp-governed-map"]
mc-hash = ["sidechain-mc-hash", "block-source"]
sidechain-rpc = ["pallet-sidechain-rpc", "block-source"]
block-participation = ["sp-block-participation"]
bridge = ["sp-partner-chains-bridge"]
