[package]
name = "partner-chains-mock-data-sources"
version.workspace = true
publish = false
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "Mock implementations of all data sources used by Partner Chains components"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sidechain-domain = { workspace = true }
sp-timestamp = { workspace = true }
sp-native-token-management = { workspace = true, optional = true }
sp-governed-map = { workspace = true, optional = true }
sidechain-mc-hash = { workspace = true, optional = true }
sp-block-participation = { workspace = true, optional = true }
pallet-sidechain-rpc = { workspace = true, optional = true }
authority-selection-inherents = { workspace = true, optional = true }

[features]
default = ["std", "block-source", "candidate-source", "governed-map", "native-token"]
std = [
	"serde_json/std",
	"sidechain-domain/std",
	"rand/std",
	"sp-native-token-management?/std",
	"sp-block-participation?/std"
]
block-source = []
candidate-source = ["authority-selection-inherents"]
governed-map = ["sp-governed-map"]
native-token = ["sp-native-token-management"]
mc-hash = ["sidechain-mc-hash"]
sidechain-rpc = ["pallet-sidechain-rpc"]
block-participation = ["sp-block-participation"]
