(function() {var implementors = {
"authority_selection_inherents":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"authority_selection_inherents/filter_invalid_candidates/enum.RegistrationDataError.html\" title=\"enum authority_selection_inherents::filter_invalid_candidates::RegistrationDataError\">RegistrationDataError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"authority_selection_inherents/filter_invalid_candidates/enum.StakeError.html\" title=\"enum authority_selection_inherents::filter_invalid_candidates::StakeError\">StakeError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"authority_selection_inherents/filter_invalid_candidates/enum.PermissionedCandidateDataError.html\" title=\"enum authority_selection_inherents::filter_invalid_candidates::PermissionedCandidateDataError\">PermissionedCandidateDataError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"authority_selection_inherents/ariadne_inherent_data_provider/enum.InherentProviderCreationError.html\" title=\"enum authority_selection_inherents::ariadne_inherent_data_provider::InherentProviderCreationError\">InherentProviderCreationError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"authority_selection_inherents/authority_selection_inputs/enum.AuthoritySelectionInputsCreationError.html\" title=\"enum authority_selection_inherents::authority_selection_inputs::AuthoritySelectionInputsCreationError\">AuthoritySelectionInputsCreationError</a>"]],
"cli_commands":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"cli_commands/key_params/enum.MainchainKeyError.html\" title=\"enum cli_commands::key_params::MainchainKeyError\">MainchainKeyError</a>"]],
"epoch_derivation":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"epoch_derivation/mainchain/enum.EpochDerivationError.html\" title=\"enum epoch_derivation::mainchain::EpochDerivationError\">EpochDerivationError</a>"]],
"main_chain_follower_api":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"main_chain_follower_api/enum.DataSourceError.html\" title=\"enum main_chain_follower_api::DataSourceError\">DataSourceError</a>"]],
"partner_chains_cli":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"partner_chains_cli/prepare_configuration/enum.PrepareConfigurationError.html\" title=\"enum partner_chains_cli::prepare_configuration::PrepareConfigurationError\">PrepareConfigurationError</a>"]],
"sidechain_mc_hash":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sidechain_mc_hash/enum.McHashInherentError.html\" title=\"enum sidechain_mc_hash::McHashInherentError\">McHashInherentError</a>"]],
"sp_block_rewards":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_block_rewards/enum.InherentError.html\" title=\"enum sp_block_rewards::InherentError\">InherentError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_block_rewards/enum.InherentProviderCreationError.html\" title=\"enum sp_block_rewards::InherentProviderCreationError\">InherentProviderCreationError</a>"]],
"sp_native_token_management":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_native_token_management/enum.IDPCreationError.html\" title=\"enum sp_native_token_management::IDPCreationError\">IDPCreationError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_native_token_management/enum.InherentError.html\" title=\"enum sp_native_token_management::InherentError\">InherentError</a>"]],
"sp_session_validator_management":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_session_validator_management/enum.InherentError.html\" title=\"enum sp_session_validator_management::InherentError\">InherentError</a>"]],
"sp_session_validator_management_query":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_session_validator_management_query/types/enum.RegistrationError.html\" title=\"enum sp_session_validator_management_query::types::RegistrationError\">RegistrationError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()