[package]
name = "plutus"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
hex = { workspace = true }
minicbor = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
num-traits = { workspace = true }
