[package]
name = "sp-block-producer-fees"
version.workspace = true
license = "Apache-2.0"
description = "Primitives for the block producer fees"
readme = "README.md"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = ["parity-scale-codec/std", "sp-api/std", "sp-std/std"]
