
//! Autogenerated weights for pallet_block_production_log
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-11, STEPS: `5000`, REPEAT: `2000`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `lglo-framework13`, CPU: `AMD Ryzen 7 7840U w/ Radeon  780M Graphics`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/sidechain-runtime/sidechain_runtime.compact.compressed.wasm
// --pallet
// pallet_block_production_log
// --extrinsic
// *
// --steps=5000
// --repeat=2000
// --wasm-execution=compiled
// --output
// toolkit/pallets/block-production-log/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_block_production_log.
pub trait WeightInfo {
	fn append() -> Weight;
}

/// Weights for pallet_block_production_log using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `BlockProductionLog::LatestBlock` (r:1 w:1)
	/// Proof: `BlockProductionLog::LatestBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Aura::CurrentSlot` (r:1 w:0)
	/// Proof: `Aura::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BlockProductionLog::Log` (r:1 w:1)
	/// Proof: `BlockProductionLog::Log` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn append() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2507`
		//  Estimated: `3992`
		// Minimum execution time: 7_153_000 picoseconds.
		Weight::from_parts(7_564_000, 3992)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `BlockProductionLog::LatestBlock` (r:1 w:1)
	/// Proof: `BlockProductionLog::LatestBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Aura::CurrentSlot` (r:1 w:0)
	/// Proof: `Aura::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BlockProductionLog::Log` (r:1 w:1)
	/// Proof: `BlockProductionLog::Log` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn append() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2507`
		//  Estimated: `3992`
		// Minimum execution time: 7_153_000 picoseconds.
		Weight::from_parts(7_564_000, 3992)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
