[package]
name = "sidechain-mc-hash"
version = "1.7.0"
description = "Logic for putting a main chain block reference in digest and inherent data"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-partner-chains-consensus-aura = { workspace = true, features = ["std"] , version = "1.7.0" }
sidechain-domain = { workspace = true, features = ["std"] , version = "1.7.0" }
sp-consensus = { workspace = true }
sp-blockchain = { workspace = true }
sp-inherents = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-timestamp = { workspace = true }
thiserror = { workspace = true }
derive-new = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
derive-new = { workspace = true }

[features]
mock = ["derive-new"]
serde = ["dep:serde"]
