[package]
name = "sp-native-token-management"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true, optional = true }
envy = { workspace = true, optional = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sidechain-domain = { workspace = true }
sp-api = { workspace = true }
sp-inherents = { workspace = true }
sp-runtime = { workspace = true }
thiserror = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
sp-version = { workspace = true, optional = true }
derive-new = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
default = ["std"]
std = [
    "async-trait",
    "parity-scale-codec/std",
    "scale-info/std",
    "sidechain-domain/std",
    "sp-api/std",
    "sp-inherents/std",
    "sp-runtime/std",
    "thiserror",
    "envy",
    "sp-version",
    "sp-version/std",
    "serde",
]
serde = ["dep:serde", "scale-info/serde", "sidechain-domain/serde"]
mock = []
