
//! Autogenerated weights for pallet_partner_chains_bridge
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 50.0.0
//! DATE: 2025-08-25, STEPS: `500`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Nikolaoss-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/partner-chains-demo-runtime/partner_chains_demo_runtime.compact.compressed.wasm
// --pallet
// pallet_partner_chains_bridge
// --extrinsic
// *
// --steps=500
// --repeat=200
// --wasm-execution=compiled
// --output
// toolkit/bridge/pallet/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_partner_chains_bridge.
pub trait WeightInfo {
	fn handle_transfers(t: u32, s: u32, ) -> Weight;
	fn set_main_chain_scripts() -> Weight;
}

/// Weights for pallet_partner_chains_bridge using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// The range of component `t` is `[1, 256]`.
	/// The range of component `s` is `[1, 256]`.
	fn handle_transfers(t: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(1_914_402, 0)
			// Standard Error: 8
			.saturating_add(Weight::from_parts(166, 0).saturating_mul(t.into()))
			// Standard Error: 8
			.saturating_add(Weight::from_parts(127, 0).saturating_mul(s.into()))
	}
	/// Storage: `Bridge::MainChainScriptsConfiguration` (r:0 w:1)
	/// Proof: `Bridge::MainChainScriptsConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// The range of component `t` is `[1, 256]`.
	/// The range of component `s` is `[1, 256]`.
	fn handle_transfers(t: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(1_914_402, 0)
			// Standard Error: 8
			.saturating_add(Weight::from_parts(166, 0).saturating_mul(t.into()))
			// Standard Error: 8
			.saturating_add(Weight::from_parts(127, 0).saturating_mul(s.into()))
	}
	/// Storage: `Bridge::MainChainScriptsConfiguration` (r:0 w:1)
	/// Proof: `Bridge::MainChainScriptsConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
