[package]
name = "sp-block-participation"
version.workspace = true
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }

async-trait = { workspace = true }
parity-scale-codec = { workspace = true }
sp-inherents = { workspace = true }
sp-runtime = { workspace = true }
sidechain-domain = { workspace = true }
sp-api = { workspace = true }
log = { workspace = true }
sp-consensus-slots = { workspace = true }
scale-info = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
pretty_assertions = { workspace = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "sp-inherents/std",
    "sp-runtime/std",
    "sp-runtime/std",
    "sp-api/std",
    "log/std",
    "sp-consensus-slots/std",
    "sidechain-domain/std",
    "scale-info/std"
]
