[package]
name = "sp-session-validator-management-query"
version = "1.7.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
serde_json = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-session-validator-management = { workspace = true, features = ["std"] , version = "1.7.0" }
sp-sidechain = { workspace = true, features = ["std"] , version = "1.7.0" }
sidechain-domain = { workspace = true, features = ["std"] , version = "1.7.0" }
sidechain-block-search = { workspace = true , version = "1.7.0" }
authority-selection-inherents = { workspace = true, features = ["std"] , version = "1.7.0" }
thiserror = { workspace = true }
plutus = { workspace = true , version = "1.7.0" }

[dev-dependencies]
sp-std = { workspace = true }
hex-literal = { workspace = true }
minicbor = { workspace = true }
plutus-datum-derive = { workspace = true , version = "1.7.0" }
tokio = { workspace = true }
authority-selection-inherents = { workspace = true, features = ["mock"] , version = "1.7.0" }
