
//! Autogenerated weights for pallet_block_producer_fees
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-05-05, STEPS: `5000`, REPEAT: `2000`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `framework-13`, CPU: `AMD Ryzen 7 7840U w/ Radeon  780M Graphics`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/partner-chains-demo-runtime/partner_chains_demo_runtime.compact.compressed.wasm
// --pallet
// pallet_block_producer_fees
// --extrinsic
// *
// --steps=5000
// --repeat=2000
// --wasm-execution=compiled
// --output
// toolkit/block-producer-fees/pallet/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_block_producer_fees.
pub trait WeightInfo {
	fn set_fee() -> Weight;
}

/// Weights for pallet_block_producer_fees using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `BlockProducerFees::FeesChanges` (r:1 w:1)
	/// Proof: `BlockProducerFees::FeesChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Aura::CurrentSlot` (r:1 w:0)
	/// Proof: `Aura::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1046`
		//  Estimated: `4511`
		// Minimum execution time: 11_562_000 picoseconds.
		Weight::from_parts(12_423_000, 4511)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `BlockProducerFees::FeesChanges` (r:1 w:1)
	/// Proof: `BlockProducerFees::FeesChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Aura::CurrentSlot` (r:1 w:0)
	/// Proof: `Aura::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1046`
		//  Estimated: `4511`
		// Minimum execution time: 11_562_000 picoseconds.
		Weight::from_parts(12_423_000, 4511)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
