[package]
name = "sidechain-slots"
version = "1.7.0"
license = "Apache-2.0"
description = "Sidechain slots and epoch calcuations"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sidechain-domain = { workspace = true , version = "1.7.0" }
sp-api = { workspace = true }
sp-blockchain = { workspace = true, optional = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true, features = ["serde"]}
sp-consensus-slots = { workspace = true }
serde = { workspace = true, optional = true }
envy = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ['std']
std = [
    'sidechain-domain/std',
    'scale-info/std',
    'sp-api/std',
	'sp-blockchain',
    'sp-core/std',
    'sp-consensus-slots/std',
    'envy',
]
serde = [
    "dep:serde",
    "scale-info/serde",
    "sp-core/serde",
]
