[package]
name = "pallet-block-participation"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-std = { workspace = true }
sp-block-participation = { workspace = true }
pallet-block-production-log = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
pretty_assertions = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-std/std",
    "sp-block-participation/std",
    "pallet-block-production-log/std"
]
runtime-benchmarks = ["frame-benchmarking"]
