name: "Publish to GHCR"
description: "Pulls the partner-chains-node Docker image from ECR and pushes it to GHCR with appropriate tags."

inputs:
  sha:
    description: "Commit SHA"
    required: true
  tag:
    description: "Release Tag"
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Pull Docker Image from ECR
      run: |
        docker pull ${{ env.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }}
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Docker Image for GHCR
      run: |
        docker tag ${{ env.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }} ghcr.io/${{ github.repository }}/partner-chains-node:latest
        docker tag ${{ env.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }} ghcr.io/${{ github.repository }}/partner-chains-node:${{ inputs.sha }}
        docker tag ${{ env.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }} ghcr.io/${{ github.repository }}/partner-chains-node:${{ inputs.tag }}
      shell: bash

    - name: Push Tagged Images to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/partner-chains-node:latest
        docker push ghcr.io/${{ github.repository }}/partner-chains-node:${{ inputs.sha }}
        docker push ghcr.io/${{ github.repository }}/partner-chains-node:${{ inputs.tag }}
      shell: bash
