name: "Build and Upload PC Artifacts"
description: "Build and upload partner-chains artifacts for Linux, macOS x86_64, and macOS arm64"
inputs:
  tag:
    description: "partner-chains release tag to append to artifact name"
    required: true
  sha:
    description: "Commit SHA to checkout"
    required: true
  os:
    description: "Operating system for the build (linux-x86_64, linux-arm64, macos-x86_64, macos-arm64)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha }}
    - name: Set filename variables
      shell: bash
      run: |
        if [[ "${{ inputs.os }}" == "linux-x86_64" ]]; then
          echo "PARTNER_CHAINS_NODE=partner-chains-node-${{ inputs.tag }}-x86_64-linux" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "linux-arm64" ]]; then
          echo "PARTNER_CHAINS_NODE=partner-chains-node-${{ inputs.tag }}-aarch64-linux" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "macos-x86_64" ]]; then
          echo "PARTNER_CHAINS_NODE=partner-chains-node-${{ inputs.tag }}-x86_64-apple-darwin" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "macos-arm64" ]]; then
          echo "PARTNER_CHAINS_NODE=partner-chains-node-${{ inputs.tag }}-aarch64-apple-darwin" >> $GITHUB_ENV
        fi
    - name: Install protoc
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        if [[ "${{ inputs.os }}" == "linux-x86_64" || "${{ inputs.os }}" == "linux-arm64" ]]; then
          sudo apt-get install -y protobuf-compiler
        elif [[ "${{ inputs.os }}" == "macos-x86_64" ]]; then
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-osx-x86_64.zip
          unzip protoc-21.3-osx-x86_64.zip -d $HOME/protoc
          sudo mv $HOME/protoc/bin/protoc /usr/local/bin/protoc
        elif [[ "${{ inputs.os }}" == "macos-arm64" ]]; then
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-osx-aarch_64.zip
          unzip protoc-21.3-osx-aarch_64.zip -d $HOME/protoc
          sudo mv $HOME/protoc/bin/protoc /usr/local/bin/protoc
        fi
    # Install LLVM for macOS builds - using specific version 19.1.7
    - name: Install LLVM for macOS
      if: startsWith(inputs.os, 'macos')
      shell: bash
      run: |
        # Install specific LLVM version 19 to match working environment
        brew install llvm@19
        echo "LLVM_PATH=$(brew --prefix llvm@19)" >> $GITHUB_ENV
        # Ensure LLVM is found first in PATH to avoid Apple's default version
        echo "$(brew --prefix llvm@19)/bin" >> $GITHUB_PATH
        # Add to bash profile for any subshells
        echo 'export PATH="$(brew --prefix llvm@19)/bin:$PATH"' >> ~/.bash_profile
        source ~/.bash_profile
        # Configure compiler flags
        echo "CC=$(brew --prefix llvm@19)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm@19)/bin/clang++" >> $GITHUB_ENV
        echo "LLVM_CONFIG=$(brew --prefix llvm@19)/bin/llvm-config" >> $GITHUB_ENV
        # Verify the version matches your working environment
        $(brew --prefix llvm@19)/bin/clang --version
        # Create a configuration file like in your working environment
        mkdir -p /opt/homebrew/etc/clang
        echo "# clang configuration for GitHub Actions" > /opt/homebrew/etc/clang/arm64-apple-darwin24.cfg
    - name: Build partner-chains-node
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        if [[ "${{ inputs.os }}" == "linux-x86_64" ]]; then
          rustup target add x86_64-unknown-linux-gnu
          cargo build -p partner-chains-node --locked --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/partner-chains-node $PARTNER_CHAINS_NODE
          chmod +x $PARTNER_CHAINS_NODE
        elif [[ "${{ inputs.os }}" == "linux-arm64" ]]; then
          rustup target add aarch64-unknown-linux-gnu
          cargo build -p partner-chains-node --locked --release --target aarch64-unknown-linux-gnu
          cp target/aarch64-unknown-linux-gnu/release/partner-chains-node $PARTNER_CHAINS_NODE
          chmod +x $PARTNER_CHAINS_NODE
        elif [[ "${{ inputs.os }}" == "macos-x86_64" ]]; then
          rustup target add x86_64-apple-darwin
          # Environment variables are already set in the LLVM installation step
          # Use RUST_FLAGS to ensure the right toolchain is used
          RUSTFLAGS="-C linker=${LLVM_PATH}/bin/clang" \
          cargo build -p partner-chains-node --locked --release --target x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/partner-chains-node $PARTNER_CHAINS_NODE
          chmod +x $PARTNER_CHAINS_NODE
        elif [[ "${{ inputs.os }}" == "macos-arm64" ]]; then
          rustup target add aarch64-apple-darwin
          # Environment variables are already set in the LLVM installation step
          # Use RUST_FLAGS to ensure the right toolchain is used
          RUSTFLAGS="-C linker=${LLVM_PATH}/bin/clang" \
          cargo build -p partner-chains-node --locked --release --target aarch64-apple-darwin
          cp target/aarch64-apple-darwin/release/partner-chains-node $PARTNER_CHAINS_NODE
          chmod +x $PARTNER_CHAINS_NODE
        fi
    - name: Upload partner-chains-node artifact
      uses: actions/upload-artifact@v4
      with:
        name: partner-chains-node-${{ inputs.os }}-artifact
        path: ${{ env.PARTNER_CHAINS_NODE }}