#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "$_")
SHARED_DIR="$SCRIPT_DIR/data/shared"

DOT_ENV="$SCRIPT_DIR/.env"
if [ -f "$DOT_ENV" ]; then
    source "$DOT_ENV"
    export DB_SYNC_POSTGRES_CONNECTION_STRING="postgres://postgres:$POSTGRES_PASSWORD@localhost:$POSTGRES_PORT/cexplorer"
    export DOLOS_MINIBF_URL="localhost:$DOLOS_MINIBF_PORT"
else
    echo "$DOT_ENV file missing!"
fi

RUNTIME_VALUES="$SCRIPT_DIR/runtime-values"
for VAR in NATIVE_TOKEN_POLICY_ID NATIVE_TOKEN_ASSET_NAME MC__FIRST_EPOCH_TIMESTAMP_MILLIS; do
    if [ -f "$RUNTIME_VALUES/$VAR" ]; then
        echo "$VAR"=$(cat "$RUNTIME_VALUES/$VAR" )
        export "$VAR"=$(cat "$RUNTIME_VALUES/$VAR" )
    else
        echo "Couldn't load value for environment variable $VAR"
    fi
done

SHELLEY_GENESIS_FILE="$SCRIPT_DIR/configurations/genesis/shelley/genesis.json"
if [ -f "$SHELLEY_GENESIS_FILE" ]; then
    export MC__SLOT_DURATION_MILLIS=$(jq '.slotLength * 1000' $SHELLEY_GENESIS_FILE)
    export MC__EPOCH_DURATION_MILLIS=$(jq '.epochLength * 1000' $SHELLEY_GENESIS_FILE)
    export CARDANO_SECURITY_PARAMETER=$(jq '.securityParam' $SHELLEY_GENESIS_FILE)
    export CARDANO_ACTIVE_SLOTS_COEFF=$(jq '.activeSlotsCoeff' $SHELLEY_GENESIS_FILE)
else
    echo "Shelley genesis file $SHELLEY_GENESIS_FILE missing!"
fi

export CARDANO_DATA_SOURCE="db-sync"

export BLOCK_STABILITY_MARGIN=0
export MC__FIRST_EPOCH_NUMBER=0
export MC__FIRST_SLOT_NUMBER=0


PC_GENESIS_UTXO_FILE="$RUNTIME_VALUES/genesis.utxo"
if [ -f "$PC_GENESIS_UTXO_FILE" ]; then
    export GENESIS_UTXO=$(cat $PC_GENESIS_UTXO_FILE)
else
    echo "Partner Chain genesis file $PC_GENESIS_UTXO_FILE not present"
fi

ADDRESSES_FILE="$RUNTIME_VALUES/addresses.json"
if [ -f "$ADDRESSES_FILE" ]; then
    export COMMITTEE_CANDIDATE_ADDRESS=$(jq -r '.addresses.CommitteeCandidateValidator' "$ADDRESSES_FILE")
    export D_PARAMETER_POLICY_ID=$(jq -r '.policyIds.DParameter' "$ADDRESSES_FILE")
    export PERMISSIONED_CANDIDATES_POLICY_ID=$(jq -r '.policyIds.PermissionedCandidates' "$ADDRESSES_FILE")
    export ILLIQUID_SUPPLY_VALIDATOR_ADDRESS=$(jq -r '.addresses.IlliquidCirculationSupplyValidator' "$ADDRESSES_FILE")
    export ILLIQUID_CIRCULATION_SUPPLY_VALIDATOR_ADDRESS=$(echo $ILLIQUID_SUPPLY_VALIDATOR_ADDRESS)
    export GOVERNED_MAP_VALIDATOR_ADDRESS=$(jq -r '.addresses.GovernedMapValidator' "$ADDRESSES_FILE")
    export GOVERNED_MAP_POLICY_ID=$(jq -r '.policyIds.GovernedMap' "$ADDRESSES_FILE")
else
    echo "Addresses file not found: $ADDRESSES_FILE"
fi

SPEC_FILE="$RUNTIME_VALUES/chain-spec.json"
if [ -f "$SPEC_FILE" ]; then
    export SLOTS_PER_EPOCH=$(jq -r ".genesis.runtimeGenesis.config.sidechain.epochDurationMillis / ${MC__SLOT_DURATION_MILLIS:=6000}" "$SPEC_FILE")
else
    echo "Partner Chain chain spec file $SPEC_FILE not present"
fi
