name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
jobs:
  build:
    runs-on: nixos
    steps:
      - name: cache cargo build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build
        run: nix develop -c bash -c "cargo build && cargo test && cargo clippy"
