name: Build and Publish to GHCR Public Repository

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to build from"
        required: true
        type: string
      publish_to_ghcr:
        description: "Publish to GitHub Container Registry"
        default: true
        type: boolean
      ghcr_tag:
        description: "Tag for GHCR image"
        required: true
        type: string

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Setup Earthly
        uses: ./.github/earthly-setup
        with:
          ssh_key: ${{ secrets.SUBSTRATE_REPO_SSH_KEY }}
          config_tar: ${{ secrets.EARTHLY_TAR }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          FORCE_COLOR: 1

      - name: Build
        if: ${{ inputs.publish_to_ghcr }}
        env:
          EARTHLY_CI: true
          EARTHLY_PUSH: true
          EARTHLY_OUTPUT: true
        run: |
          repository_name="${GITHUB_REPOSITORY##*/}"
          target_image="ghcr.io/${{ github.repository }}/$repository_name-node"
          custom_tag="${{ inputs.ghcr_tag }}"

          earthly -P +docker --image="$target_image" --tags="latest $custom_tag" --PROFILE=production
