# Workflow not to be executed manually, but by the release.yml workflow

name: "Release: Publish Image to GHCR (Don't run manually!)"

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The SHA of the commit to build'
        required: true
        type: string
      tag:
        description: 'The tag for the release'
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Specified Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Publish to GHCR
        uses: ./.github/actions/images/publish-ghcr
        with:
          sha: ${{ github.event.inputs.sha }}
          tag: ${{ github.event.inputs.tag }}
        env:
          AWS_REGION: "eu-central-1"
          ECR_REGISTRY_SECRET: ${{ secrets.ECR_REGISTRY_SECRET }}
          AWS_ROLE_ARN_SECRET: ${{ secrets.AWS_ROLE_ARN_SECRET }}
          ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}